###############################################################################   
# Licensed Materials - Property of IBM   #   
# (C) Copyright IBM Corp. 2021. All Rights Reserved.   #  
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.   #   
###############################################################################

version: '3'
services:

  #############################################################################################################
  # The "pc" container is running the Workflow Process Service (authoring trial) image
  #############################################################################################################
  pc:
    image: icr.io/icp4ba/workflow-ps-trial:23.0.2-amd64 
    container_name: pc
    hostname: pc
    depends_on:
      - opensearch
    ports:
      - "9443:9443"
    stop_grace_period: 2m
    environment:
      - LICENSE=accept
      ###########################################################################################################
      # EXTERNAL_HOSTNAME must not be localhost if you want to access Workplace or BA Studio from a web browser
      # which is not running on the docker host.
      # In such case, replace EXTERNAL_HOSTNAME with the actual hostname of the docker host.
      ###########################################################################################################
      - EXTERNAL_HOSTNAME=localhost
      - EXTERNAL_HTTPS_PORT=9443
      # PFS properties
      - PFS_ENABLE=true
      - PFS_REMOTEELASTICSEARCH_ENDPOINTS=http://opensearch:9200
      # The hostname used by PFS to access Workflow Process Service (authoring trial):
      - INTERNAL_HOSTNAME=localhost
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M

  # The "opensearch" container is required by PFS to provide the federated data repository
  opensearch:
    image: opensearchproject/opensearch:2.7.0
    container_name: opensearch
    hostname: opensearch
    #############################################################################################################
    # This container is for demo only and does not provide SSL support or authentication, therefore the 9200 port
    # is not exposed externally.
    # If despite the security risk you want to expose the unsecured Opensearch API you can comment out the
    # following 2 lines
    #############################################################################################################
    # ports:
    #   - "9200:9200"
    environment:
      - plugins.security.disabled=true
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  default:
    driver: bridge
