###############################################################################   
# Licensed Materials - Property of IBM   #   
# (C) Copyright IBM Corp. 2021. All Rights Reserved.   #  
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.   #   
###############################################################################

version: '3'
services:

  #############################################################################################################
  # The "pc" container is running the Workflow Process Service (authoring trial) image
  #############################################################################################################
  pc:
    image: icr.io/icp4ba/workflow-ps-trial:22.0.1-amd64 
    container_name: pc
    hostname: pc
    depends_on:
      - elasticsearch
    ports:
      - "9443:9443"
    stop_grace_period: 2m
    volumes:
      - pc_data:/shared/custom:z
      - postgres_data:/var/lib/pgsql/12/data:z
    environment:
      - LICENSE=accept
      ###########################################################################################################
      # EXTERNAL_HOSTNAME must not be localhost if you want to access Workplace or BA Studio from a web browser
      # which is not running on the docker host.
      # In such case, replace EXTERNAL_HOSTNAME with the actual hostname of the docker host.
      ###########################################################################################################
      - EXTERNAL_HOSTNAME=localhost
      - EXTERNAL_HTTPS_PORT=9443
      # PFS properties
      - PFS_ENABLE=true
      - PFS_REMOTEELASTICSEARCH_ENDPOINTS=http://elasticsearch:9200
      # The hostname used by PFS to access Workflow Process Service (authoring trial):
      - INTERNAL_HOSTNAME=localhost
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M

  # The "elasticsearch" container required by PFS
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    hostname: elasticsearch
    #############################################################################################################
    # Elasticsearch OSS image does not provide SSL support, therefore the 9200 port is not exposed externally
    # If despite the security risk you want to expose the unsecured Elasticsearch API you can comment out the
    # following 2 lines
    #############################################################################################################
    # ports:
    #   - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:z
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  pc_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/"
  postgres_data:
  elasticsearch_data:

networks:
  default:
    driver: bridge
